spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-63-34-97-163.eu-west-1.compute.amazonaws.com:5432/dc722o1i9ca56n
    username: lkcwpwqzizapmr
    password: 24848ee43bfc89cc56aaee0601a577c074c98de203cfec3670177ae0d885c0c8
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true