spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ADVdesignerBD
    username: postgres
    password: 1234abcd
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true 